### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by nlehuby** [simonpoole/preset-utils#2]
When I try to use the following command from the readme, I get an `java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException` error from java.

`java -cp preset-utils-0.28.0.jar ch.poole.osm.presetutils.Preset2Pot -h`

Is there something wrong in the doc or in the released jar ?

**Comment by simonpoole** [comment]
Hi @nlehuby I'll need to check that, though imho it should work, but maybe there's an issue with the jar. You are using the jar from the "Releases"?

**Comment by nlehuby** [comment]
yes, the 0.28.0 one from the github releases

**Comment by simonpoole** [comment]
The problem was simply that I hadn't generated the fat jar, done that now and added it to the release. As the read me says you need to use the jar files with _all_ in the name to get the fat jar for command line use..

Sorry for the problem.

**Comment by nlehuby** [comment]
Thanks :+1:
