### ISSUE TITLE
Website doesn't display nested groups correctly

### ISSUE THREAD

**Issue by riQQ** [simonpoole/preset-utils#5]
Picnic Site, Picnic Table, etc. are part of the `Leisure` group and should not be displayed below the `Playground Equipment` subgroup.

![Screenshot of website with error marked](https://github.com/simonpoole/beautified-JOSM-preset/assets/3404787/aecbdf03-e306-43d4-ae21-7eb7c816e3bc)

**Comment by simonpoole** [comment]
That needs to be fixed in https://github.com/simonpoole/preset-utils moving the issue there.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/preset-utils/commit/4037dbd3bf1f38e37c33a7dbcaf95e3d88f74274 at least fixes things so far that you get a new line when returning to the enclosing group.
