### ISSUE TITLE
Preset utils ends with an error message

### ISSUE THREAD

**Issue by Heiner-Sch** [simonpoole/preset-utils#7]
Hi,
I try to run 
java -cp preset-utils-all-0.40.1.jar ch.poole.osm.presetutils.Preset2Pot -h
but this ends with an error message.

I think it's because I've downloaded
preset-utils-0.40.1.jar
from Releases.

But also 
java -cp preset-utils-0.40.1.jar ch.poole.osm.presetutils.Preset2Pot -h
ends with an error.

Is there a mistake in the repository?

**Comment by simonpoole** [comment]
What's the error message?

**Comment by Heiner-Sch** [comment]
Sorry for the late feedback. It wasn't possible earier.

Since v0.41.0 is online, this issue is useless.
So I'll close it.
